apiVersion: v1
kind: Service
metadata:
  name: capi-visualizer-nodeport
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: capi-visualizer
