# pyright: reportUndefinedVariable=false

load('./Tiltfile-vote', 'voteAppURL')

load('./Tiltfile-result', 'resultAppURL')

# TODO: export actual variable or figure out how to avoid placeholder
load('./Tiltfile-worker', 'placeholder')
