apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: ${CLUSTER_NAME}-${POOL_NAME}
  namespace: default
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: ${CLUSTER_NAME}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: ${CLUSTER_NAME}-${POOL_NAME}
      version: v1.26.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: ${CLUSTER_NAME}-${POOL_NAME}
  namespace: default
spec:
  enableNodePublicIP: false
  name: ${POOL_NAME}
  mode: ${POOL_MODE:=User}
  osDiskSizeGB: ${POOL_DISK_SIZE:=30}
  sku: ${POOL_MACHINE_SKU:=Standard_A2_v2}
  scaling:
    minSize: ${POOL_MIN_SIZE:=1}
    maxSize: ${POOL_MAX_SIZE:=2}
